# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Copy the source files and tsconfig BEFORE npm install
COPY src ./src
COPY tsconfig.json ./

# Install dependencies
RUN npm install

# Compile TypeScript to JavaScript
RUN npm run build

# Use a smaller image for the runtime
FROM node:18-alpine AS runtime

# Set the working directory
WORKDIR /app

# Create a non-root user to run the application
RUN addgroup -g 1001490000 -S app && adduser -u 1001490000 -G app -S -D app

# Copy the build output and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Copy the entrypoint script if necessary
COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./

# Adjust ownership to the non-root user
RUN chown -R app:app /app

# Switch to the non-root user
USER app

ENV CLICKUP_TEAM_ID="9011970959"
ENV ENABLE_SSE="true"
ENV ENABLE_STDIO="false"
ENV PORT="3231"
ENV LOG_LEVL="DEBUG"
ENV HEADER_AUTHENTICATION="true"

# Expose the ports used by the server (HTTP 3231 by default, optional HTTPS 3443)
EXPOSE 3231 3443

# Health check endpoint (requires wget from busybox/alpine)
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD wget -qO- http://127.0.0.1:${PORT}/health || exit 1

# Define the command to run the application
CMD ["node", "build/index.js"]
