apiVersion: v1
kind: Secret
metadata:
  name: clickup-mcp-secret
type: Opaque
stringData:
  CLICKUP_TEAM_ID: "9011970959"
  ENABLE_SSE: "true"
  ENABLE_STDIO: "false"
  PORT: "3231"
  LOG_LEVL: "DEBUG"
  HEADER_AUTHENTICATION: "true"
  HOST: "0.0.0.0"
