apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickup-mcp-deployment
  labels:
    app: clickup-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickup-mcp
  template:
    metadata:
      labels:
        app: clickup-mcp
    spec:
      containers:
        - name: clickup-mcp
          imagePullPolicy: IfNotPresent
          env:
            - name: CLICKUP_TEAM_ID
              value: "9011970959"
            - name: ENABLE_SSE
              value: "true"
            - name: ENABLE_STDIO
              value: "false"
            - name: PORT
              value: "3231"
            - name: LOG_LEVL
              value: "DEBUG"
            - name: HEADER_AUTHENTICATION
              value: "true"
            - name: HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 3231            
      serviceAccountName: deployer
      serviceAccount: deployer
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101      